Repository prgrms-be-devcourse/NBE5-7-2-Team05, pull requests merged in 2025-05, with the labels that each got.

#8 Feat : Follow 기능 구현
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/FollowResponseDto.java
  src/main/java/io/powerrangers/backend/entity/Follow.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/test/java/io/powerrangers/backend/service/FollowServiceTests.java
Labels: feature

#11 Feat: 댓글, 대댓글 게시 기능 구현
  build.gradle
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentCreateRequestDto.java
  src/main/java/io/powerrangers/backend/entity/Comment.java
  src/main/java/io/powerrangers/backend/repository/CommentRepository.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/test/java/io/powerrangers/backend/CommentServiceTests.java
Labels: feature

#13 Feat : 언팔로우 기능 구현
  build.gradle
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/FollowResponseDto.java
  src/main/java/io/powerrangers/backend/entity/Follow.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/test/java/io/powerrangers/backend/service/FollowServiceTests.java
Labels: feature

#18 Feat: 댓글 조회 기능 구현
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/dao/CommentRepository.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentResponseDto.java
  src/main/java/io/powerrangers/backend/repository/CommentRepository.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.java
Labels: feature

#21 Feat : 팔로워 목록 조회
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dto/UserFollowResponseDto.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/test/java/io/powerrangers/backend/service/FollowServiceTests.java
Labels: feature

#30 Feat: 댓글 수정 기능 구현
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateResponseDto.java
  src/main/java/io/powerrangers/backend/entity/Comment.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.java
Labels: feature

#37 Feat : 응답 및 예외 처리 커스텀마이징
  src/main/java/io/powerrangers/backend/config/Oauth2SuccessHandler.java
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dto/BaseResponse.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/SuccessCode.java
  src/main/java/io/powerrangers/backend/dto/TaskCreateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.java
  src/main/java/io/powerrangers/backend/exception/CustomException.java
  src/main/java/io/powerrangers/backend/exception/ErrorCode.java
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/java/io/powerrangers/backend/service/ContextUtil.java
  src/main/java/io/powerrangers/backend/service/CustomOauth2UserService.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature

#43 Feat: 댓글 삭제 구현
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.java
Labels: feature

#41 Feat : Access Token 재발급 기능 구현
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/service/ContextUtil.java
  src/main/java/io/powerrangers/backend/service/UserService.java
  src/test/java/io/powerrangers/backend/service/UserServiceTests.java
Labels: feature

#34 Feat: 할일 인증 이미지 등록 구현
  build.gradle
  src/main/java/io/powerrangers/backend/config/S3Config.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/entity/Task.java
  src/main/java/io/powerrangers/backend/service/S3Service.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/test/java/io/powerrangers/backend/service/UserServiceTests.java
Labels: feature

#49 Feat : 삭제 시 Cascade 되도록 디버깅 & 인증 방식 개선
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/dao/TokenRepository.java
  src/main/java/io/powerrangers/backend/dao/adapter/RefreshTokenRepositoryAdapter.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskCreateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentCreateRequestDto.java
  src/main/java/io/powerrangers/backend/entity/Comment.java
  src/main/java/io/powerrangers/backend/entity/RefreshToken.java
  src/main/java/io/powerrangers/backend/entity/Task.java
  src/main/java/io/powerrangers/backend/entity/User.java
  src/main/java/io/powerrangers/backend/exception/ErrorCode.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature

#55 Feat : 프로필 수정 최적화 및 닉네임 검색/댓글 응답 구조 개선
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dao/UserRepository.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentResponseDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateResponseDto.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature

#54 Feat : mainpage UI 구현
  src/main/resources/static/css/mypage.css
  src/main/resources/static/mypage.html
Labels: feature

#59 Feat : 인증 관련 예외 처리 및 이미지 예외 처리 개선
  src/main/java/io/powerrangers/backend/config/JwtAuthenticationFilter.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/exception/AuthTokenException.java
  src/main/java/io/powerrangers/backend/exception/ErrorCode.java
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.java
  src/main/java/io/powerrangers/backend/service/ContextUtil.java
  src/main/java/io/powerrangers/backend/service/CustomOauth2UserService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserDetailsFactory.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature

#66 Feat : 공개 범위 설정에 따라 할 일, 할 일 인증 이미지 조회 API 구현
  src/main/java/io/powerrangers/backend/config/Oauth2SuccessHandler.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/dao/TaskRepository.java
  src/main/java/io/powerrangers/backend/dto/TaskImageResponseDto.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature, BE

#68 Feat: 프론트 token 재발급 구현
  src/main/java/io/powerrangers/backend/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/token-reissue.js
Labels: feature, FE

#69 Feat : 조회할 때 공개 범위 설정에 맞게 조회하도록 메서드 추가 및 특정 유저의 특정 날짜 할 일 조회하는 API 구현
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dao/TaskRepository.java
  src/main/java/io/powerrangers/backend/entity/BaseEntity.java
  src/main/java/io/powerrangers/backend/exception/ErrorCode.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: feature, BE

#73 Feat: 달력을 누르면 해당 날짜의 할일 리스트 조회
  src/main/resources/static/js/index.js
Labels: feature, FE

#70 Fix : 프로필 이미지 저장 방식 변경 및 수정
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.java
  src/main/java/io/powerrangers/backend/service/S3Service.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: fix, BE

#80 Refactor: ErrorCode 통합
  src/main/java/io/powerrangers/backend/config/JwtAuthenticationFilter.java
  src/main/java/io/powerrangers/backend/exception/ErrorCode.java
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.java
  src/main/java/io/powerrangers/backend/service/UserDetailsFactory.java
  src/main/java/io/powerrangers/backend/service/UserService.java
Labels: refactor

#76 Refactor : base_url yml파일로 관리
  src/main/java/io/powerrangers/backend/config/Oauth2SuccessHandler.java
Labels: refactor

#74 Feat: 팔로워,팔로잉목록, 유저 검색기능
  src/main/java/io/powerrangers/backend/config/JwtAuthenticationFilter.java
  src/main/java/io/powerrangers/backend/config/SecurityConfig.java
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/resources/static/css/follow-list.css
  src/main/resources/static/css/search.css
  src/main/resources/static/css/serach-followlist.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/follow-list.html
  src/main/resources/static/images/default-profile.png
  src/main/resources/static/index.html
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/follow.js
  src/main/resources/static/js/search.js
  src/main/resources/static/search.html
Labels: FE

#78 Refactor: SuccessCode메시지삭제
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dto/BaseResponse.java
  src/main/java/io/powerrangers/backend/dto/SuccessCode.java
Labels: refactor

#83 Refactor : RequestDTO에 @Builder 삭제 및 Repository에서 DTO 사용하지 않도록 수정
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/LogoutRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskCreateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/UserFollowResponseDto.java
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
Labels: refactor, BE

#87 Feat: 컨트롤러에서 와일드카드("?") 제거
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/dto/BaseResponse.java
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.java
Labels: refactor, BE

#90 Feat: mainpage 기능 구현
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentResponseDto.java
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/main.js
Labels: feature, FE

#100 Refactor: search.css수정(팔로우,팔로잉버튼)
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/resources/static/css/search.css
Labels: refactor, FE

#91 Fix : 유저 이미지 변경하지 않았을 때, 프로필 이미지 null이 되는 현상 해결
  src/main/java/io/powerrangers/backend/dto/TaskImageResponseDto.java
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/UserService.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/images/home-icon.png
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
  src/main/resources/templates/updatemypage.html
Labels: fix, BE

#106 Feat : 팔로우 관계인지 판단하는 API
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/dto/FollowCheckResponseDto.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
Labels: feature, BE

#108 Design : 메인페이지 카테고리 구조 변경
  src/main/resources/static/css/index.css
  src/main/resources/static/js/main.js
Labels: FE

#111 Fix : Mypage 팔로워, ToDo 기능 수정
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: fix, FE

#109 Refactor: 팔로우리스트, 검색페이지 버튼추가, 디자인수정
  src/main/resources/static/css/index.css
  src/main/resources/static/css/search.css
  src/main/resources/static/follow-list.html
  src/main/resources/static/js/follow.js
  src/main/resources/static/js/search.js
  src/main/resources/static/search.html
Labels: refactor, FE

#117 Feat: 프로필 클릭시 해당 사용자의 할 일 목록으로 이동 버튼 활성화
  src/main/resources/static/css/search.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/follow.js
  src/main/resources/static/js/search.js
Labels: feature, FE

#113 Refactor : 메인페이지의 메시지 구체화
  src/main/resources/static/js/main.js
Labels: refactor, FE

#125 Feat: 특정 월의 날짜별 할 일 개수 조회
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dao/TaskRepository.java
  src/main/java/io/powerrangers/backend/dto/TaskSummaryResponseDto.java
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/TaskService.java
Labels: feature, BE

#129 Feat : 회원 탈퇴 기능 구현
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: feature, FE

#132 Feat: 할 일 개수표시 프론트코드 구현
  src/main/resources/static/css/index.css
  src/main/resources/static/js/index.js
Labels: feature, FE

#133 Feat : Memories 사진 누르면 할 일 정보 띄우는 기능 구현
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: feature, FE

#139 Fix: index.html 유저아이디추가하여 리다이렉션(홈버튼)
  src/main/resources/static/js/follow.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/search.js
  src/main/resources/static/js/user.js
Labels: fix, FE

#141 Fix: 시뮬레이션 중 발생한 버그 수정
  src/main/resources/static/js/main.js
  src/main/resources/static/js/user-page.js
  src/main/resources/static/user-page.html
Labels: fix, FE

#144 Refactor: 요청 baseurl 삭제
  src/main/resources/static/js/main.js
Labels: refactor, FE

#145 Fix: 로컬스토리지 UserId 세팅
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/resources/static/js/initial-auth.js
  src/main/resources/static/js/main.js
Labels: fix, BE, FE

#150 Fix : 할 일 추가/삭제 시 달력 즉시 렌더링 (할 일 개수 반영)
  src/main/resources/static/js/main.js
Labels: fix, BE

#148 Fix : 다른 사람 페이지에서 내 할 일 우선 X, 해당 유저의 할 일이 뜨도록 하기
  src/main/resources/static/js/index.js
  src/main/resources/static/js/main.js
Labels: fix, BE
